// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBrLmOEL5DbInhTbMWckYYJK4NFsneseIE",
  authDomain: "yourtraveltalk-bd.firebaseapp.com",
  databaseURL: "https://yourtraveltalk-bd-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "yourtraveltalk-bd",
  storageBucket: "yourtraveltalk-bd.firebasestorage.app",
  messagingSenderId: "120666230864",
  appId: "1:120666230864:web:4ffad9df3de93a5cc2c155",
  measurementId: "G-7FE9CQDBL8"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yzE0vK7XcqoQYEYGTfdgrNlqZ2DetpY',
    appId: '1:120666230864:android:4d3984b37af711a4c2c155',
    messagingSenderId: '120666230864',
    projectId: 'yourtraveltalk-bd',
    databaseURL: 'https://yourtraveltalk-bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yourtraveltalk-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8Dn-1O1_Obfn8xuKvBuU7NUL9MJ9MDw',
    appId: '1:754718364327:ios:4fcbf000fd1b0040830182',
    messagingSenderId: '754718364327',
    projectId: 'travel-talk-bd',
    databaseURL: 'https://travel-talk-bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travel-talk-bd.firebasestorage.app',
    iosBundleId: 'com.example.traveltalkbd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8Dn-1O1_Obfn8xuKvBuU7NUL9MJ9MDw',
    appId: '1:754718364327:ios:4fcbf000fd1b0040830182',
    messagingSenderId: '754718364327',
    projectId: 'travel-talk-bd',
    databaseURL: 'https://travel-talk-bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travel-talk-bd.firebasestorage.app',
    iosBundleId: 'com.example.traveltalkbd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK7Y8G8ARN7GUzyfGsEaAQgw16XqaA9Nc',
    appId: '1:754718364327:web:22ee0eac61055a9a830182',
    messagingSenderId: '754718364327',
    projectId: 'travel-talk-bd',
    authDomain: 'travel-talk-bd.firebaseapp.com',
    databaseURL: 'https://travel-talk-bd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'travel-talk-bd.firebasestorage.app',
    measurementId: 'G-7HKPNNBEZE',
  );
}
